// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-sdmoIsaHcUbcfqvol_TDhiMEZe8d9E',
    appId: '1:1083752226602:web:c60f8903cdd756a10e8853',
    messagingSenderId: '1083752226602',
    projectId: 'xkxim-f8033',
    authDomain: 'xkxim-f8033.firebaseapp.com',
    storageBucket: 'xkxim-f8033.appspot.com',
    measurementId: 'G-CRFSX36XZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWjEYHsGZeRVh44rPjB8pk8h7KQiJuDBQ',
    appId: '1:1083752226602:android:54c334c42baa3e5f0e8853',
    messagingSenderId: '1083752226602',
    projectId: 'xkxim-f8033',
    storageBucket: 'xkxim-f8033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXLcy9KQ6w24OXMips7xupnLAObPn7eN8',
    appId: '1:1083752226602:ios:7131c96adba4fc9f0e8853',
    messagingSenderId: '1083752226602',
    projectId: 'xkxim-f8033',
    storageBucket: 'xkxim-f8033.appspot.com',
    iosClientId: '1083752226602-ku48dcfikpa0rask8umjqhm32jvdmu2k.apps.googleusercontent.com',
    iosBundleId: 'imflutter.xkim.com.imFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXLcy9KQ6w24OXMips7xupnLAObPn7eN8',
    appId: '1:1083752226602:ios:7131c96adba4fc9f0e8853',
    messagingSenderId: '1083752226602',
    projectId: 'xkxim-f8033',
    storageBucket: 'xkxim-f8033.appspot.com',
    iosClientId: '1083752226602-ku48dcfikpa0rask8umjqhm32jvdmu2k.apps.googleusercontent.com',
    iosBundleId: 'imflutter.xkim.com.imFlutter',
  );
}
